# Generated by Django 4.1.7 on 2023-03-31 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransferGuide', '0004_course_equivalentcourse_course_nonequivalentcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='equivalentCourse',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='nonEquivalentCourse',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
