# Generated by Django 4.1.7 on 2023-03-31 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TransferGuide', '0005_alter_course_equivalentcourse_and_more'),
        ('TransferGuide', '0007_requestform_studentemail_alter_requestform_pending'),
    ]

    operations = [
    ]
